### ISSUE TITLE
 Call to undefined method Mbarwick83\TwitterApi\Facades\TwitterApi::accessToken()

### ISSUE THREAD

**Issue by angelkurten** [mbarwick83/twitter-api#2]
Call to undefined method Mbarwick83\TwitterApi\Facades\TwitterApi::accessToken()

![Image of Yaktocat](http://image.prntscr.com/image/5d3a50e672f144f18e52517f23e27d62.png)

**Comment by angelkurten** [comment]
Solved!

**Comment by Hugolopez2** [comment]
"Call to undefined method Mbarwick83\TwitterApi\Facades\TwitterApi::accessToken()" I have this error, how you did to resolve?
