### ISSUE TITLE
Chunked Upload Timeout Issues

### ISSUE THREAD

**Issue by g33kidd** [mbarwick83/twitter-api#4]
I'm building an automated system to upload images/videos to twitter, but I seem to run into issues when the video uploading starts. The error in question is a Timeout error, I assume this error is from twitter.

So my files range anywhere from 5MB to 12MB and none of the file sizes I have tried seem to work. Has anybody experienced this issue? Or is there a way to get around the timeout?

This is what I get: `Operation timed out after 5004 milliseconds with 0 bytes received`

**Comment by mbarwick83** [comment]
This is very likely your application and/or server settings. Not a library issue.
