### ISSUE TITLE
Failing Install: Class Syntax Issue

### ISSUE THREAD

**Issue by matthewjamesr** [mbarwick83/twitter-api#5]
Script php artisan optimize handling the post-update-cmd event returned with an error

                                                                            
  [RuntimeException]                                                        
  Error Output: PHP Fatal error:  Class 'Mbarwick83\TwitterApi\TwitterApiS  
  erviceProvider' not found in /home/matthewjames/workspace/odins-eye/vue-  
  starter-laravel-api/vendor/laravel/framework/src/Illuminate/Foundation/P  
  roviderRepository.php on line 146

**Comment by mbarwick83** [comment]
Did you follow the installation and configuration steps exactly as highlighted in readme? Try `php artisan vendor:publish --provider="Mbarwick83\TwitterApi\TwitterApiServiceProvider"`

**Comment by matthewjamesr** [comment]
Directions followed, still failing on `composer update`. Side note: `vendor:publish` is broken by default (forgot to mention).

Case mismatch solved by changing filename in src/conifg.

**Comment by mbarwick83** [comment]
Can you submit a PR wth the breaking change?

**Comment by mbarwick83** [comment]
Add blank values in your env file for the ones found in config. Sorry, config should have default if no env values found.

**Comment by mel-pashtet** [comment]
Hi. How use method "get" of this plugin. please add examle of usage.
For example how I can use this
$twitter = new TwitterApi();
$r = $twitter->get('account/verify_credentials');
