### ISSUE TITLE
Not working in case-sensitive file system (like Linux)

### ISSUE THREAD

**Issue by crash13override** [mbarwick83/twitter-api#7]
I was experiencing a weird problem where everything would run perfectly on my localhost, but then on my production server it would fail and throw this error

`Class 'Mbarwick83\TwitterApi\Lib\Config' not found`

After a lot of debugging I found out that it was caused by the fact that the "lib" folder that contains the Config.php file, needs to be renamed to "Lib" with capital "L" in order to work, otherwise it won't find the Config class.

Can you please update the folder name so that it can fix the issue with case-sensitive OS?

thanks a lot for your great work with this API!!!

**Comment by mbarwick83** [comment]
Got it fixed (I believe). 👍

**Comment by crash13override** [comment]
thanks! :)
